// Generated by https://quicktype.io

export interface DashboardSummaryType {
  numberOfOrders:           number;
  paidOrders:               number;
  notPaidOrders:            number;
  numberOfClients:          number;
  numberOfProducts:         number;
  productsWithNoInventory:  number;
  productsWithLowInventory: number;
}
